spring.application.name=demo

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5430/
spring.datasource.username=example
spring.datasource.password=secret2
spring.datasource.platform=postgres
spring.datasource.driver-class-name=org.postgresql.Driver